# Workflow name
name: 'Chromatic'

# Event for the workflow
on:
  pull\_request:
    branches:
      - main
# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm i
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: '🚀storybook: ${{ steps.chromatic.outputs.storybookUrl }}'
